#!/bin/bash

set -e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done

if [[ -z $1 ]]; then
	DOCKER_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	REPO_ROOT="$( cd -P "$( dirname "$DOCKER_DIR" )" && pwd )"
else
	REPO_ROOT=$1
fi

DOCKER_VERSION=$(docker version -f "{{.Server.Version}}")
DOCKER_MAJOR=$(echo "$DOCKER_VERSION"| cut -d'.' -f 1)

if [ "${DOCKER_MAJOR}" -ge 19 ]; then
    runtime="--gpus=all"
else
    runtime="--runtime=nvidia"
fi

# no need to do `xhost +` anymore
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
touch $XAUTH
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

IMAGE="openmvs-ubuntu:latest"
RUNTIME=$runtime

docker run ${RUNTIME} --privileged -it --rm \
			-w /opt/src \
	   		-e NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics \
            --volume=${REPO_ROOT}/:/opt/src/ \
            --volume=$XSOCK:$XSOCK:rw \
            --volume=$XAUTH:$XAUTH:rw \
	    	--ipc=host \
            --shm-size=4gb \
            --env="XAUTHORITY=${XAUTH}" \
            --env="DISPLAY=unix$DISPLAY" \
	    	--entrypoint /bin/bash \
            ${IMAGE}
